logging:
  pattern:
    console: "[Practical Java] %clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
    file: "[Practical Java] %clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  file:
    name: log/feed-tube.log
  category:
    org:
      springframework:
        data:
          mongodb: DEBUG

spring:
  main:
    banner-mode: OFF
  jackson:
    property-naming-strategy: SNAKE_CASE
  data:
    mongodb:
      host: localhost
      port: 27017
      database: feedTubeDB

server:
  port: 8080
